### ISSUE TITLE
Float8 support?

### ISSUE THREAD

**Issue by gvilums** [starkat99/half-rs#115]
Are there any plans to add `float8` support to this library? I would be willing to do the implementation work, I'm just wondering if it makes sense to do that as a PR to this crate or whether I should create a new crate. We're already using `half` for fp16 and bf16 support, so adding fp8 would be a natural fit.

**Comment by cksac** [comment]
in StableHLO, there are few 8-bit float variants
```
FloatType ::= 'f8E3M4' | 'f8E4M3' | 'f8E4M3FN' | 'f8E4M3FNUZ' | 'f8E4M3B11FNUZ'
            | 'f8E5M2' | 'f8E5M2FNUZ' | 'bf16' | 'f16' | 'f32' | 'f64'
```
https://github.com/openxla/stablehlo/blob/main/docs/spec.md

**Comment by gvilums** [comment]
good point - it would probably make sense to focus on the most widely used ones, which are E4M3 and E5M2 from my understanding

**Comment by cksac** [comment]
there has new crate for float8 https://github.com/EricLBuehler/float8, it provide F8E4M3 and F8E5M2.

**Comment by gvilums** [comment]
nice, looks like what I'm looking for 👍
