### ISSUE TITLE
Convert an u16 array to f16 array

### ISSUE THREAD

**Issue by johannesvollmer** [starkat99/half-rs#14]
I am currently implementing a popular file format in Rust which stores binary f16 arrays. As `byteorder` does not support f16, I need to read these f16 arrays as u16 arrays and then convert them to f16, in order to correctly handle endianness.

I wondered if there could be some functionality in this library, which prevents users to just do `array.iter().map(|u| f16::from_bits(u)).collect::<Vec<f16>>()`. This code iterates the whole array and allocates a new vector, but (I assume that) in memory, not a single bit is changed. All it probably does is basically copying the contents of the array element by element. But all it needs to do is really just interpreting the bits in a different way by representing it with a different type at compile time. 

Is it maybe possible to reinterpret an array of u16 as an array of f16 by simply unsafely casting the raw pointers?

If not, certainly it's possible to provide an `F16Slice <'a> (&'a [u16])` which maybe even implements `::std::ops::Index` with `f16::from_bits(self.0[index])`, or something similar.

On the other hand, I can imagine that my use case is rather rare and not many people need to convert between large arrays of u16 and f16. Anyways, what do you think of that?

_Also, Please correct me if I have overlooked something._

**Comment by johannesvollmer** [comment]
Update: implementing `::std::ops::Index` probably does not work naively, because `Index` returns a ŕeference and not a value.

**Comment by starkat99** [comment]
Yes, it should be safe to reinterpret the whole array. And this use case is probably common, so probably should add some slice/array conversion helpers

**Comment by johannesvollmer** [comment]
That would be great. I think the biggest challenge here is proving that it will work everywhere, the actual implementation is just three or less lines per conversion.

**Comment by johannesvollmer** [comment]
I have prototyped the implementation including some simple tests, see [my fork](https://github.com/johannesvollmer/half-rs/commit/5b92d968bfaed2a67d5be97efc03c4f681280a23).

As this commit also supports converting `Vec`s, it contains a conditional module that is only included when `feature="std"` is enabled. The tests were performed with Rust version 1.15.0.

Please note that I am not that experienced in writing unsafe Rust code, and that maybe the code only works because I did not test it well enough.

Would you welcome a a pull request from that fork?

**Comment by starkat99** [comment]
Yes, a pull request would be great
