### ISSUE TITLE
Mutable Slice Conversion

### ISSUE THREAD

**Issue by johannesvollmer** [starkat99/half-rs#16]
In my last pull request I blindly stated that conversion of mutable slices could not be implemented because I thought it would violate mutability rules. 

As it turns out, the borrow checker is really smart, and __it is indeed possible to reinterpret mutable slices without incorrect behaviour__. I need this functionality for efficient binary deserialization of `f16` numbers.

I have implemented `from_bits_mut` and `to_bits_mut` in `f16::slice` in [my fork](https://github.com/johannesvollmer/half-rs/commit/90155f3504cff2aaafb735594595387d5dec3212). I'd like to send a pull request, if you approve.

**Comment by starkat99** [comment]
Sounds good to me, send the PR
