### ISSUE TITLE
Debug for f16 and bf16 should convert to f32, like Display

### ISSUE THREAD

**Issue by charles-r-earp** [starkat99/half-rs#37]
Debug is used more than Display since it can be derived, and is also used for containers. The interior u16 is an implementation detail, and almost certainly the user wants to see the numerical value not the bit value when using Debug, for example when working with vecs or arrays. Assertions, errors, all work with Debug, and this makes those unreadable.

**Comment by starkat99** [comment]
Fixed in 1.7.0
