### ISSUE TITLE
Enable x86 F16C hardware intrinsics on stable Rust

### ISSUE THREAD

**Issue by starkat99** [starkat99/half-rs#54]
F16C hardware intrinsics still not stabilized, just needs stabilization PR https://github.com/rust-lang/stdarch/issues/1234

Probably the biggest priority for crate now that `const` conversions are done.

**Comment by starkat99** [comment]
Opened PRs for stabilization: https://github.com/rust-lang/stdarch/pull/1366 and https://github.com/rust-lang/rust/pull/106323

**Comment by mert-kurttutan** [comment]
@starkat99 just wanted to see if you have any non-public update on this one. F16C intrinsic (when using rust nightly) provides really good performance improvements for my project.

**Comment by mert-kurttutan** [comment]
Seems like your PR is merged. Any plan to release a new version for this feature ?

**Comment by Shnatsel** [comment]
The necessary intrinsics have shipped on stable in 1.70.0
