### ISSUE TITLE
How do you cast into f16?

### ISSUE THREAD

**Issue by BA8F0D39** [starkat99/half-rs#69]
How do you cast a f32 variable into a f16 variable?

```
	use half::f16;
	use num::traits::FromPrimitive;
	use half::*;
	use half;
	
	let a: f16 = (0.2f32).into();

	println!("a {}",a);
```

 |     let a: f16 =  (0.2f32).into();
   |                   ^^^^^^^^ ---- required by a bound introduced by this call
   |                   |
   |                   the trait `From<f32>` is not implemented for `f16`
   |
   = help: the following other types implement trait `From<T>`:
             <f16 as From<i8>>
             <f16 as From<u8>>
   = note: required for `f32` to implement `Into<f16>`

**Comment by starkat99** [comment]
The conversion from `f32` to `f16` is lossy, so there's no direct `From<>` implementation. Use `f16::from_f32` instead.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e1145cc6fe3ce6de9ddf731e534765e3

You can go from `f16` to `f32` with a `into()` call though, as the reverse is not lossy.

**Comment by IvanMalison** [comment]
@starkat99 not having a from implementation can be kind of limiting in some cases. Do you really think it would that bad to have a lossy implementation?
