### ISSUE TITLE
Improve CI solution for other architectures

### ISSUE THREAD

**Issue by starkat99** [starkat99/half-rs#72]
See if there's a Github action runner host that can do AArch64 images, would speed up CI immensely by avoiding running on QEMU. Compile times are just atrocious, even for small crate like this. Or find some other solution for testing AArch64.

**Comment by Shnatsel** [comment]
CircleCI seems to have an ARM free tier: https://circleci.com/pricing/

You can find more options here: https://github.com/ligurio/awesome-ci

**Comment by starkat99** [comment]
I looked into CircleCI, it didn't require a separate ARM machine, they do have ARM machines in their cloud, so this is all setup now. _Way_ faster than trying to do it in Github actions on top of QEMU
